### ISSUE TITLE
Typo in the suspend attribute of the CronJob

### ISSUE THREAD

**Issue by ja-michel** [DrPsychick/charts#7]
When `suspended` is used K8 complains that the attribute is unknown.

https://github.com/DrPsychick/charts/blob/7e9ee186bf2b0073c80c8778346be52c5a099126/drpsychick/cronjobs/templates/cronjob.yaml#L34-L36

The docs state that the correct attribute is `suspend` (`.spec.suspend`). See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#suspend

**Comment by DrPsychick** [comment]
Hey @ja-michel , thanks for pointing that out, fix is on the way.
